"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from mongoengine import connect

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p4la%4bkkuadn9^ow9@sd033#z15jz60b7+t(%tb3pc^39p7fi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']

import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
}

# connect(
# #     # host="mongodb+srv://debabratasenapati2021_db_user:iYc0KfKFbSMik5ez@cluster0.f0jhytt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0",
#         db='Pyblog',
#         host="mongodb+srv://debabratasenapati2021_db_user:iYc0KfKFbSMik5ez@cluster0.f0jhytt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
#         # host ="mongodb://debabratasenapati2021_db_user:iYc0KfKFbSMik5ez@ac-q6zcjne-shard-00-00.f0jhytt.mongodb.net:27017,ac-q6zcjne-shard-00-01.f0jhytt.mongodb.net:27017,ac-q6zcjne-shard-00-02.f0jhytt.mongodb.net:27017/?ssl=true&replicaSet=atlas-g87yl8-shard-0&authSource=admin&appName=Cluster0"
# )

# connect(
#     db='Pyblog',
#     host="mongodb+srv://debabratasenapati2021_db_user:iYc0KfKFbSMik5ez@cluster0.f0jhytt.mongodb.net/Pyblog?retryWrites=true&w=majority"
# )
# connect(
#     db="pythonBlogDb",
#     host="localhost",
#     port=27017
# )

# uri = "mongodb://debabratasenapati2021_db_user:sHK9hMg2Y4YM2v6K@ac-q6zcjne-shard-00-00.f0jhytt.mongodb.net:27017,ac-q6zcjne-shard-00-01.f0jhytt.mongodb.net:27017,ac-q6zcjne-shard-00-02.f0jhytt.mongodb.net:27017/?ssl=true&replicaSet=atlas-g87yl8-shard-0&authSource=admin&appName=Cluster0"

# when post on docker
connect(
    db="pythonBlogDb",
    host="host.docker.internal",
    port=27017
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
